//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sitio_Privado.ConsultaSaldosFondosMutuos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tann_fondos_mutuosSoap", Namespace="http://servicios.tanner/ffmm")]
    public partial class tann_fondos_mutuos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cn_saldo_ffmm_rvOperationCompleted;
        
        private System.Threading.SendOrPostCallback cn_saldo_ffmm_rfOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tann_fondos_mutuos() {
            this.Url = global::Sitio_Privado.Properties.Settings.Default.Sitio_Privado_ConsultaSaldosFondosMutuos_tann_fondos_mutuos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cn_saldo_ffmm_rvCompletedEventHandler cn_saldo_ffmm_rvCompleted;
        
        /// <remarks/>
        public event cn_saldo_ffmm_rfCompletedEventHandler cn_saldo_ffmm_rfCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner/ffmm/cn_saldo_ffmm_rv", RequestNamespace="http://servicios.tanner/ffmm", ResponseNamespace="http://servicios.tanner/ffmm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public saldo_ffmm[] cn_saldo_ffmm_rv(int rut) {
            object[] results = this.Invoke("cn_saldo_ffmm_rv", new object[] {
                        rut});
            return ((saldo_ffmm[])(results[0]));
        }
        
        /// <remarks/>
        public void cn_saldo_ffmm_rvAsync(int rut) {
            this.cn_saldo_ffmm_rvAsync(rut, null);
        }
        
        /// <remarks/>
        public void cn_saldo_ffmm_rvAsync(int rut, object userState) {
            if ((this.cn_saldo_ffmm_rvOperationCompleted == null)) {
                this.cn_saldo_ffmm_rvOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncn_saldo_ffmm_rvOperationCompleted);
            }
            this.InvokeAsync("cn_saldo_ffmm_rv", new object[] {
                        rut}, this.cn_saldo_ffmm_rvOperationCompleted, userState);
        }
        
        private void Oncn_saldo_ffmm_rvOperationCompleted(object arg) {
            if ((this.cn_saldo_ffmm_rvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cn_saldo_ffmm_rvCompleted(this, new cn_saldo_ffmm_rvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner/ffmm/cn_saldo_ffmm_rf", RequestNamespace="http://servicios.tanner/ffmm", ResponseNamespace="http://servicios.tanner/ffmm", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public saldo_ffmm[] cn_saldo_ffmm_rf(int rut) {
            object[] results = this.Invoke("cn_saldo_ffmm_rf", new object[] {
                        rut});
            return ((saldo_ffmm[])(results[0]));
        }
        
        /// <remarks/>
        public void cn_saldo_ffmm_rfAsync(int rut) {
            this.cn_saldo_ffmm_rfAsync(rut, null);
        }
        
        /// <remarks/>
        public void cn_saldo_ffmm_rfAsync(int rut, object userState) {
            if ((this.cn_saldo_ffmm_rfOperationCompleted == null)) {
                this.cn_saldo_ffmm_rfOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncn_saldo_ffmm_rfOperationCompleted);
            }
            this.InvokeAsync("cn_saldo_ffmm_rf", new object[] {
                        rut}, this.cn_saldo_ffmm_rfOperationCompleted, userState);
        }
        
        private void Oncn_saldo_ffmm_rfOperationCompleted(object arg) {
            if ((this.cn_saldo_ffmm_rfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cn_saldo_ffmm_rfCompleted(this, new cn_saldo_ffmm_rfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner/ffmm")]
    public partial class saldo_ffmm {
        
        private string descripcionField;
        
        private string tipoField;
        
        private string cta_pisysField;
        
        private decimal valor_cuotaField;
        
        private decimal saldo_cuotaField;
        
        private string rentaField;
        
        private decimal pesosField;
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public string cta_pisys {
            get {
                return this.cta_pisysField;
            }
            set {
                this.cta_pisysField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_cuota {
            get {
                return this.valor_cuotaField;
            }
            set {
                this.valor_cuotaField = value;
            }
        }
        
        /// <remarks/>
        public decimal saldo_cuota {
            get {
                return this.saldo_cuotaField;
            }
            set {
                this.saldo_cuotaField = value;
            }
        }
        
        /// <remarks/>
        public string renta {
            get {
                return this.rentaField;
            }
            set {
                this.rentaField = value;
            }
        }
        
        /// <remarks/>
        public decimal pesos {
            get {
                return this.pesosField;
            }
            set {
                this.pesosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void cn_saldo_ffmm_rvCompletedEventHandler(object sender, cn_saldo_ffmm_rvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cn_saldo_ffmm_rvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cn_saldo_ffmm_rvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public saldo_ffmm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((saldo_ffmm[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void cn_saldo_ffmm_rfCompletedEventHandler(object sender, cn_saldo_ffmm_rfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cn_saldo_ffmm_rfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cn_saldo_ffmm_rfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public saldo_ffmm[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((saldo_ffmm[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591