//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sitio_Privado.ConsultaSaldosFondosPrivados {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tann_fondo_invprivSoap", Namespace="http://servicios.tanner/fondoinvpriv")]
    public partial class tann_fondo_invpriv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback saldo_fipOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tann_fondo_invpriv() {
            this.Url = global::Sitio_Privado.Properties.Settings.Default.Sitio_Privado_ConsultaSaldosFondosPrivados_tann_fondo_invpriv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event saldo_fipCompletedEventHandler saldo_fipCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner/fondoinvpriv/saldo_fip", RequestNamespace="http://servicios.tanner/fondoinvpriv", ResponseNamespace="http://servicios.tanner/fondoinvpriv", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _resumen saldo_fip(string rutc, System.DateTime fecha) {
            object[] results = this.Invoke("saldo_fip", new object[] {
                        rutc,
                        fecha});
            return ((_resumen)(results[0]));
        }
        
        /// <remarks/>
        public void saldo_fipAsync(string rutc, System.DateTime fecha) {
            this.saldo_fipAsync(rutc, fecha, null);
        }
        
        /// <remarks/>
        public void saldo_fipAsync(string rutc, System.DateTime fecha, object userState) {
            if ((this.saldo_fipOperationCompleted == null)) {
                this.saldo_fipOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsaldo_fipOperationCompleted);
            }
            this.InvokeAsync("saldo_fip", new object[] {
                        rutc,
                        fecha}, this.saldo_fipOperationCompleted, userState);
        }
        
        private void Onsaldo_fipOperationCompleted(object arg) {
            if ((this.saldo_fipCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.saldo_fipCompleted(this, new saldo_fipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner/fondoinvpriv")]
    public partial class _resumen {
        
        private string rutField;
        
        private decimal totalField;
        
        private System.DateTime fechasaldoField;
        
        private _saldo[] detalleField;
        
        /// <remarks/>
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
            }
        }
        
        /// <remarks/>
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechasaldo {
            get {
                return this.fechasaldoField;
            }
            set {
                this.fechasaldoField = value;
            }
        }
        
        /// <remarks/>
        public _saldo[] Detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner/fondoinvpriv")]
    public partial class _saldo {
        
        private string nombre_fondoField;
        
        private decimal cuentaField;
        
        private decimal val_cuotaField;
        
        private decimal sal_cuotaField;
        
        private decimal sal_pesosField;
        
        /// <remarks/>
        public string nombre_fondo {
            get {
                return this.nombre_fondoField;
            }
            set {
                this.nombre_fondoField = value;
            }
        }
        
        /// <remarks/>
        public decimal cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public decimal val_cuota {
            get {
                return this.val_cuotaField;
            }
            set {
                this.val_cuotaField = value;
            }
        }
        
        /// <remarks/>
        public decimal sal_cuota {
            get {
                return this.sal_cuotaField;
            }
            set {
                this.sal_cuotaField = value;
            }
        }
        
        /// <remarks/>
        public decimal sal_pesos {
            get {
                return this.sal_pesosField;
            }
            set {
                this.sal_pesosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void saldo_fipCompletedEventHandler(object sender, saldo_fipCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class saldo_fipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal saldo_fipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _resumen Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_resumen)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591