//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sitio_Privado.DocumentosPendientesFirma {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tann_documentosSoap", Namespace="http://servicios.tanner.cl/documentos")]
    public partial class tann_documentos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cns_operacion_pendienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback cns_operaciones_pendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback cns_contratos_pendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback cns_operacion_firmadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cns_documento_leidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cns_firmar_documentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cns_firmar_contratoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tann_documentos() {
            this.Url = global::Sitio_Privado.Properties.Settings.Default.Sitio_Privado_DocumentosPendientesFirma_tann_documentos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cns_operacion_pendienteCompletedEventHandler cns_operacion_pendienteCompleted;
        
        /// <remarks/>
        public event cns_operaciones_pendientesCompletedEventHandler cns_operaciones_pendientesCompleted;
        
        /// <remarks/>
        public event cns_contratos_pendientesCompletedEventHandler cns_contratos_pendientesCompleted;
        
        /// <remarks/>
        public event cns_operacion_firmadaCompletedEventHandler cns_operacion_firmadaCompleted;
        
        /// <remarks/>
        public event cns_documento_leidoCompletedEventHandler cns_documento_leidoCompleted;
        
        /// <remarks/>
        public event cns_firmar_documentoCompletedEventHandler cns_firmar_documentoCompleted;
        
        /// <remarks/>
        public event cns_firmar_contratoCompletedEventHandler cns_firmar_contratoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/documentos/cns_operacion_pendiente", RequestNamespace="http://servicios.tanner.cl/documentos", ResponseNamespace="http://servicios.tanner.cl/documentos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _operacion[] cns_operacion_pendiente(string rut) {
            object[] results = this.Invoke("cns_operacion_pendiente", new object[] {
                        rut});
            return ((_operacion[])(results[0]));
        }
        
        /// <remarks/>
        public void cns_operacion_pendienteAsync(string rut) {
            this.cns_operacion_pendienteAsync(rut, null);
        }
        
        /// <remarks/>
        public void cns_operacion_pendienteAsync(string rut, object userState) {
            if ((this.cns_operacion_pendienteOperationCompleted == null)) {
                this.cns_operacion_pendienteOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_operacion_pendienteOperationCompleted);
            }
            this.InvokeAsync("cns_operacion_pendiente", new object[] {
                        rut}, this.cns_operacion_pendienteOperationCompleted, userState);
        }
        
        private void Oncns_operacion_pendienteOperationCompleted(object arg) {
            if ((this.cns_operacion_pendienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_operacion_pendienteCompleted(this, new cns_operacion_pendienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/documentos/cns_operaciones_pendientes", RequestNamespace="http://servicios.tanner.cl/documentos", ResponseNamespace="http://servicios.tanner.cl/documentos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int cns_operaciones_pendientes(string rut) {
            object[] results = this.Invoke("cns_operaciones_pendientes", new object[] {
                        rut});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void cns_operaciones_pendientesAsync(string rut) {
            this.cns_operaciones_pendientesAsync(rut, null);
        }
        
        /// <remarks/>
        public void cns_operaciones_pendientesAsync(string rut, object userState) {
            if ((this.cns_operaciones_pendientesOperationCompleted == null)) {
                this.cns_operaciones_pendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_operaciones_pendientesOperationCompleted);
            }
            this.InvokeAsync("cns_operaciones_pendientes", new object[] {
                        rut}, this.cns_operaciones_pendientesOperationCompleted, userState);
        }
        
        private void Oncns_operaciones_pendientesOperationCompleted(object arg) {
            if ((this.cns_operaciones_pendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_operaciones_pendientesCompleted(this, new cns_operaciones_pendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/documentos/cns_contratos_pendientes", RequestNamespace="http://servicios.tanner.cl/documentos", ResponseNamespace="http://servicios.tanner.cl/documentos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int cns_contratos_pendientes(string rut) {
            object[] results = this.Invoke("cns_contratos_pendientes", new object[] {
                        rut});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void cns_contratos_pendientesAsync(string rut) {
            this.cns_contratos_pendientesAsync(rut, null);
        }
        
        /// <remarks/>
        public void cns_contratos_pendientesAsync(string rut, object userState) {
            if ((this.cns_contratos_pendientesOperationCompleted == null)) {
                this.cns_contratos_pendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_contratos_pendientesOperationCompleted);
            }
            this.InvokeAsync("cns_contratos_pendientes", new object[] {
                        rut}, this.cns_contratos_pendientesOperationCompleted, userState);
        }
        
        private void Oncns_contratos_pendientesOperationCompleted(object arg) {
            if ((this.cns_contratos_pendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_contratos_pendientesCompleted(this, new cns_contratos_pendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/documentos/cns_operacion_firmada", RequestNamespace="http://servicios.tanner.cl/documentos", ResponseNamespace="http://servicios.tanner.cl/documentos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _operacion[] cns_operacion_firmada(string rut, string fechaIni, string fechaFin) {
            object[] results = this.Invoke("cns_operacion_firmada", new object[] {
                        rut,
                        fechaIni,
                        fechaFin});
            return ((_operacion[])(results[0]));
        }
        
        /// <remarks/>
        public void cns_operacion_firmadaAsync(string rut, string fechaIni, string fechaFin) {
            this.cns_operacion_firmadaAsync(rut, fechaIni, fechaFin, null);
        }
        
        /// <remarks/>
        public void cns_operacion_firmadaAsync(string rut, string fechaIni, string fechaFin, object userState) {
            if ((this.cns_operacion_firmadaOperationCompleted == null)) {
                this.cns_operacion_firmadaOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_operacion_firmadaOperationCompleted);
            }
            this.InvokeAsync("cns_operacion_firmada", new object[] {
                        rut,
                        fechaIni,
                        fechaFin}, this.cns_operacion_firmadaOperationCompleted, userState);
        }
        
        private void Oncns_operacion_firmadaOperationCompleted(object arg) {
            if ((this.cns_operacion_firmadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_operacion_firmadaCompleted(this, new cns_operacion_firmadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/documentos/cns_documento_leido", RequestNamespace="http://servicios.tanner.cl/documentos", ResponseNamespace="http://servicios.tanner.cl/documentos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool cns_documento_leido(string rut, string codigo) {
            object[] results = this.Invoke("cns_documento_leido", new object[] {
                        rut,
                        codigo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void cns_documento_leidoAsync(string rut, string codigo) {
            this.cns_documento_leidoAsync(rut, codigo, null);
        }
        
        /// <remarks/>
        public void cns_documento_leidoAsync(string rut, string codigo, object userState) {
            if ((this.cns_documento_leidoOperationCompleted == null)) {
                this.cns_documento_leidoOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_documento_leidoOperationCompleted);
            }
            this.InvokeAsync("cns_documento_leido", new object[] {
                        rut,
                        codigo}, this.cns_documento_leidoOperationCompleted, userState);
        }
        
        private void Oncns_documento_leidoOperationCompleted(object arg) {
            if ((this.cns_documento_leidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_documento_leidoCompleted(this, new cns_documento_leidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/documentos/cns_firmar_documento", RequestNamespace="http://servicios.tanner.cl/documentos", ResponseNamespace="http://servicios.tanner.cl/documentos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _operacion[] cns_firmar_documento(string rut, string codigo) {
            object[] results = this.Invoke("cns_firmar_documento", new object[] {
                        rut,
                        codigo});
            return ((_operacion[])(results[0]));
        }
        
        /// <remarks/>
        public void cns_firmar_documentoAsync(string rut, string codigo) {
            this.cns_firmar_documentoAsync(rut, codigo, null);
        }
        
        /// <remarks/>
        public void cns_firmar_documentoAsync(string rut, string codigo, object userState) {
            if ((this.cns_firmar_documentoOperationCompleted == null)) {
                this.cns_firmar_documentoOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_firmar_documentoOperationCompleted);
            }
            this.InvokeAsync("cns_firmar_documento", new object[] {
                        rut,
                        codigo}, this.cns_firmar_documentoOperationCompleted, userState);
        }
        
        private void Oncns_firmar_documentoOperationCompleted(object arg) {
            if ((this.cns_firmar_documentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_firmar_documentoCompleted(this, new cns_firmar_documentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/documentos/cns_firmar_contrato", RequestNamespace="http://servicios.tanner.cl/documentos", ResponseNamespace="http://servicios.tanner.cl/documentos", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _operacion[] cns_firmar_contrato(string rut, string codigo) {
            object[] results = this.Invoke("cns_firmar_contrato", new object[] {
                        rut,
                        codigo});
            return ((_operacion[])(results[0]));
        }
        
        /// <remarks/>
        public void cns_firmar_contratoAsync(string rut, string codigo) {
            this.cns_firmar_contratoAsync(rut, codigo, null);
        }
        
        /// <remarks/>
        public void cns_firmar_contratoAsync(string rut, string codigo, object userState) {
            if ((this.cns_firmar_contratoOperationCompleted == null)) {
                this.cns_firmar_contratoOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_firmar_contratoOperationCompleted);
            }
            this.InvokeAsync("cns_firmar_contrato", new object[] {
                        rut,
                        codigo}, this.cns_firmar_contratoOperationCompleted, userState);
        }
        
        private void Oncns_firmar_contratoOperationCompleted(object arg) {
            if ((this.cns_firmar_contratoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_firmar_contratoCompleted(this, new cns_firmar_contratoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner.cl/documentos")]
    public partial class _operacion {
        
        private string _codeField;
        
        private string _productoField;
        
        private string _tipoField;
        
        private string _folioField;
        
        private string _fechacreField;
        
        private string _leidoField;
        
        private string _firmadoField;
        
        private string _rutaField;
        
        private string _nombrecliField;
        
        private string _resultsField;
        
        /// <remarks/>
        public string _code {
            get {
                return this._codeField;
            }
            set {
                this._codeField = value;
            }
        }
        
        /// <remarks/>
        public string _producto {
            get {
                return this._productoField;
            }
            set {
                this._productoField = value;
            }
        }
        
        /// <remarks/>
        public string _tipo {
            get {
                return this._tipoField;
            }
            set {
                this._tipoField = value;
            }
        }
        
        /// <remarks/>
        public string _folio {
            get {
                return this._folioField;
            }
            set {
                this._folioField = value;
            }
        }
        
        /// <remarks/>
        public string _fechacre {
            get {
                return this._fechacreField;
            }
            set {
                this._fechacreField = value;
            }
        }
        
        /// <remarks/>
        public string _leido {
            get {
                return this._leidoField;
            }
            set {
                this._leidoField = value;
            }
        }
        
        /// <remarks/>
        public string _firmado {
            get {
                return this._firmadoField;
            }
            set {
                this._firmadoField = value;
            }
        }
        
        /// <remarks/>
        public string _ruta {
            get {
                return this._rutaField;
            }
            set {
                this._rutaField = value;
            }
        }
        
        /// <remarks/>
        public string _nombrecli {
            get {
                return this._nombrecliField;
            }
            set {
                this._nombrecliField = value;
            }
        }
        
        /// <remarks/>
        public string _results {
            get {
                return this._resultsField;
            }
            set {
                this._resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cns_operacion_pendienteCompletedEventHandler(object sender, cns_operacion_pendienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_operacion_pendienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_operacion_pendienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _operacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_operacion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cns_operaciones_pendientesCompletedEventHandler(object sender, cns_operaciones_pendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_operaciones_pendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_operaciones_pendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cns_contratos_pendientesCompletedEventHandler(object sender, cns_contratos_pendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_contratos_pendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_contratos_pendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cns_operacion_firmadaCompletedEventHandler(object sender, cns_operacion_firmadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_operacion_firmadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_operacion_firmadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _operacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_operacion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cns_documento_leidoCompletedEventHandler(object sender, cns_documento_leidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_documento_leidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_documento_leidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cns_firmar_documentoCompletedEventHandler(object sender, cns_firmar_documentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_firmar_documentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_firmar_documentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _operacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_operacion[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void cns_firmar_contratoCompletedEventHandler(object sender, cns_firmar_contratoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_firmar_contratoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_firmar_contratoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _operacion[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_operacion[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591