//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sitio_Privado.CategoriaInversionista {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tann_catsvcSoap", Namespace="http://servicios.tanner.cl/categoria")]
    public partial class tann_catsvc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback tann_list_catOperationCompleted;
        
        private System.Threading.SendOrPostCallback tann_cns_catOperationCompleted;
        
        private System.Threading.SendOrPostCallback tann_cns_cat_cliOperationCompleted;
        
        private System.Threading.SendOrPostCallback tann_list_prodOperationCompleted;
        
        private System.Threading.SendOrPostCallback tann_cns_prodOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tann_catsvc() {
            this.Url = global::Sitio_Privado.Properties.Settings.Default.Sitio_Privado_CategoriaInversionista_tann_catsvc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event tann_list_catCompletedEventHandler tann_list_catCompleted;
        
        /// <remarks/>
        public event tann_cns_catCompletedEventHandler tann_cns_catCompleted;
        
        /// <remarks/>
        public event tann_cns_cat_cliCompletedEventHandler tann_cns_cat_cliCompleted;
        
        /// <remarks/>
        public event tann_list_prodCompletedEventHandler tann_list_prodCompleted;
        
        /// <remarks/>
        public event tann_cns_prodCompletedEventHandler tann_cns_prodCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/categoria/tann_list_cat", RequestNamespace="http://servicios.tanner.cl/categoria", ResponseNamespace="http://servicios.tanner.cl/categoria", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _categoria[] tann_list_cat() {
            object[] results = this.Invoke("tann_list_cat", new object[0]);
            return ((_categoria[])(results[0]));
        }
        
        /// <remarks/>
        public void tann_list_catAsync() {
            this.tann_list_catAsync(null);
        }
        
        /// <remarks/>
        public void tann_list_catAsync(object userState) {
            if ((this.tann_list_catOperationCompleted == null)) {
                this.tann_list_catOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontann_list_catOperationCompleted);
            }
            this.InvokeAsync("tann_list_cat", new object[0], this.tann_list_catOperationCompleted, userState);
        }
        
        private void Ontann_list_catOperationCompleted(object arg) {
            if ((this.tann_list_catCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tann_list_catCompleted(this, new tann_list_catCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/categoria/tann_cns_cat", RequestNamespace="http://servicios.tanner.cl/categoria", ResponseNamespace="http://servicios.tanner.cl/categoria", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _categoria tann_cns_cat(int ident_cat) {
            object[] results = this.Invoke("tann_cns_cat", new object[] {
                        ident_cat});
            return ((_categoria)(results[0]));
        }
        
        /// <remarks/>
        public void tann_cns_catAsync(int ident_cat) {
            this.tann_cns_catAsync(ident_cat, null);
        }
        
        /// <remarks/>
        public void tann_cns_catAsync(int ident_cat, object userState) {
            if ((this.tann_cns_catOperationCompleted == null)) {
                this.tann_cns_catOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontann_cns_catOperationCompleted);
            }
            this.InvokeAsync("tann_cns_cat", new object[] {
                        ident_cat}, this.tann_cns_catOperationCompleted, userState);
        }
        
        private void Ontann_cns_catOperationCompleted(object arg) {
            if ((this.tann_cns_catCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tann_cns_catCompleted(this, new tann_cns_catCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/categoria/tann_cns_cat_cli", RequestNamespace="http://servicios.tanner.cl/categoria", ResponseNamespace="http://servicios.tanner.cl/categoria", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _categoria tann_cns_cat_cli(int rut_cli) {
            object[] results = this.Invoke("tann_cns_cat_cli", new object[] {
                        rut_cli});
            return ((_categoria)(results[0]));
        }
        
        /// <remarks/>
        public void tann_cns_cat_cliAsync(int rut_cli) {
            this.tann_cns_cat_cliAsync(rut_cli, null);
        }
        
        /// <remarks/>
        public void tann_cns_cat_cliAsync(int rut_cli, object userState) {
            if ((this.tann_cns_cat_cliOperationCompleted == null)) {
                this.tann_cns_cat_cliOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontann_cns_cat_cliOperationCompleted);
            }
            this.InvokeAsync("tann_cns_cat_cli", new object[] {
                        rut_cli}, this.tann_cns_cat_cliOperationCompleted, userState);
        }
        
        private void Ontann_cns_cat_cliOperationCompleted(object arg) {
            if ((this.tann_cns_cat_cliCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tann_cns_cat_cliCompleted(this, new tann_cns_cat_cliCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/categoria/tann_list_prod", RequestNamespace="http://servicios.tanner.cl/categoria", ResponseNamespace="http://servicios.tanner.cl/categoria", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _producto[] tann_list_prod() {
            object[] results = this.Invoke("tann_list_prod", new object[0]);
            return ((_producto[])(results[0]));
        }
        
        /// <remarks/>
        public void tann_list_prodAsync() {
            this.tann_list_prodAsync(null);
        }
        
        /// <remarks/>
        public void tann_list_prodAsync(object userState) {
            if ((this.tann_list_prodOperationCompleted == null)) {
                this.tann_list_prodOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontann_list_prodOperationCompleted);
            }
            this.InvokeAsync("tann_list_prod", new object[0], this.tann_list_prodOperationCompleted, userState);
        }
        
        private void Ontann_list_prodOperationCompleted(object arg) {
            if ((this.tann_list_prodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tann_list_prodCompleted(this, new tann_list_prodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/categoria/tann_cns_prod", RequestNamespace="http://servicios.tanner.cl/categoria", ResponseNamespace="http://servicios.tanner.cl/categoria", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _producto tann_cns_prod(int ident_prd) {
            object[] results = this.Invoke("tann_cns_prod", new object[] {
                        ident_prd});
            return ((_producto)(results[0]));
        }
        
        /// <remarks/>
        public void tann_cns_prodAsync(int ident_prd) {
            this.tann_cns_prodAsync(ident_prd, null);
        }
        
        /// <remarks/>
        public void tann_cns_prodAsync(int ident_prd, object userState) {
            if ((this.tann_cns_prodOperationCompleted == null)) {
                this.tann_cns_prodOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontann_cns_prodOperationCompleted);
            }
            this.InvokeAsync("tann_cns_prod", new object[] {
                        ident_prd}, this.tann_cns_prodOperationCompleted, userState);
        }
        
        private void Ontann_cns_prodOperationCompleted(object arg) {
            if ((this.tann_cns_prodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tann_cns_prodCompleted(this, new tann_cns_prodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner.cl/categoria")]
    public partial class _categoria {
        
        private int identificadorField;
        
        private string descriptorField;
        
        private string comentarioField;
        
        private _producto[] productosField;
        
        /// <remarks/>
        public int identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
            }
        }
        
        /// <remarks/>
        public _producto[] Productos {
            get {
                return this.productosField;
            }
            set {
                this.productosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner.cl/categoria")]
    public partial class _producto {
        
        private int identificadorField;
        
        private string descriptorField;
        
        private string comentarioField;
        
        private string riesgoField;
        
        private _categoria[] categoriasField;
        
        /// <remarks/>
        public int identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
            }
        }
        
        /// <remarks/>
        public string riesgo {
            get {
                return this.riesgoField;
            }
            set {
                this.riesgoField = value;
            }
        }
        
        /// <remarks/>
        public _categoria[] Categorias {
            get {
                return this.categoriasField;
            }
            set {
                this.categoriasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void tann_list_catCompletedEventHandler(object sender, tann_list_catCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tann_list_catCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tann_list_catCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _categoria[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_categoria[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void tann_cns_catCompletedEventHandler(object sender, tann_cns_catCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tann_cns_catCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tann_cns_catCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _categoria Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_categoria)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void tann_cns_cat_cliCompletedEventHandler(object sender, tann_cns_cat_cliCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tann_cns_cat_cliCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tann_cns_cat_cliCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _categoria Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_categoria)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void tann_list_prodCompletedEventHandler(object sender, tann_list_prodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tann_list_prodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tann_list_prodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _producto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_producto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void tann_cns_prodCompletedEventHandler(object sender, tann_cns_prodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tann_cns_prodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tann_cns_prodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _producto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_producto)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591