//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitio_Privado.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tannercliente.cl/wstsf/tann_catsvc.asmx")]
        public string Sitio_Privado_CategoriaInversionista_tann_catsvc {
            get {
                return ((string)(this["Sitio_Privado_CategoriaInversionista_tann_catsvc"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tannercliente.cl/wstsf/tann_fondos_mutuos.asmx")]
        public string Sitio_Privado_ConsultaSaldosFondosMutuos_tann_fondos_mutuos {
            get {
                return ((string)(this["Sitio_Privado_ConsultaSaldosFondosMutuos_tann_fondos_mutuos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tannercliente.cl/wstsf/tann_indicadores.asmx")]
        public string Sitio_Privado_IndicesLiquidezSolvencia_tann_indicadores {
            get {
                return ((string)(this["Sitio_Privado_IndicesLiquidezSolvencia_tann_indicadores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tannercliente.cl/wstsf/tann_info_cliente.asmx")]
        public string Sitio_Privado_InformacionClienteAgente_tann_info_cliente {
            get {
                return ((string)(this["Sitio_Privado_InformacionClienteAgente_tann_info_cliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tannercliente.cl/wstsf/tann_documentos.asmx")]
        public string Sitio_Privado_DocumentosPendientesFirma_tann_documentos {
            get {
                return ((string)(this["Sitio_Privado_DocumentosPendientesFirma_tann_documentos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tannercliente.cl/wstsf/tann_cartola_resumida.asmx")]
        public string Sitio_Privado_CartolaResumida_tann_cartola_resumida {
            get {
                return ((string)(this["Sitio_Privado_CartolaResumida_tann_cartola_resumida"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.tannercliente.cl/wstsf/tann_circularizacion.asmx")]
        public string Sitio_Privado_CircularizacionCustodia_tann_circularizacion {
            get {
                return ((string)(this["Sitio_Privado_CircularizacionCustodia_tann_circularizacion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://apolo-cert/wstsf/tann_suscrip_firmelec.asmx")]
        public string Sitio_Privado_SuscripcionFirmaElecDoc_tann_suscrip_firmelec {
            get {
                return ((string)(this["Sitio_Privado_SuscripcionFirmaElecDoc_tann_suscrip_firmelec"]));
            }
        }
    }
}
