//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sitio_Privado.IndicesLiquidezSolvencia {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tann_indicadoresSoap", Namespace="http://servicios.tanner.cl/indicador")]
    public partial class tann_indicadores : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cns_ind_liqOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tann_indicadores() {
            this.Url = global::Sitio_Privado.Properties.Settings.Default.Sitio_Privado_IndicesLiquidezSolvencia_tann_indicadores;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cns_ind_liqCompletedEventHandler cns_ind_liqCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/indicador/cns_ind_liq", RequestNamespace="http://servicios.tanner.cl/indicador", ResponseNamespace="http://servicios.tanner.cl/indicador", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _indicadores cns_ind_liq(string xfecha) {
            object[] results = this.Invoke("cns_ind_liq", new object[] {
                        xfecha});
            return ((_indicadores)(results[0]));
        }
        
        /// <remarks/>
        public void cns_ind_liqAsync(string xfecha) {
            this.cns_ind_liqAsync(xfecha, null);
        }
        
        /// <remarks/>
        public void cns_ind_liqAsync(string xfecha, object userState) {
            if ((this.cns_ind_liqOperationCompleted == null)) {
                this.cns_ind_liqOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_ind_liqOperationCompleted);
            }
            this.InvokeAsync("cns_ind_liq", new object[] {
                        xfecha}, this.cns_ind_liqOperationCompleted, userState);
        }
        
        private void Oncns_ind_liqOperationCompleted(object arg) {
            if ((this.cns_ind_liqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_ind_liqCompleted(this, new cns_ind_liqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner.cl/indicador")]
    public partial class _indicadores {
        
        private string _rutempField;
        
        private string _nomempField;
        
        private double _adrsietediasField;
        
        private double _pexsietediasField;
        
        private double _addifField;
        
        private double _accifField;
        
        private double _totpasexField;
        
        private double _patrliqField;
        
        private double _moncobpartField;
        
        private double _patdepField;
        
        private string _fechaField;
        
        /// <remarks/>
        public string _rutemp {
            get {
                return this._rutempField;
            }
            set {
                this._rutempField = value;
            }
        }
        
        /// <remarks/>
        public string _nomemp {
            get {
                return this._nomempField;
            }
            set {
                this._nomempField = value;
            }
        }
        
        /// <remarks/>
        public double _adrsietedias {
            get {
                return this._adrsietediasField;
            }
            set {
                this._adrsietediasField = value;
            }
        }
        
        /// <remarks/>
        public double _pexsietedias {
            get {
                return this._pexsietediasField;
            }
            set {
                this._pexsietediasField = value;
            }
        }
        
        /// <remarks/>
        public double _addif {
            get {
                return this._addifField;
            }
            set {
                this._addifField = value;
            }
        }
        
        /// <remarks/>
        public double _accif {
            get {
                return this._accifField;
            }
            set {
                this._accifField = value;
            }
        }
        
        /// <remarks/>
        public double _totpasex {
            get {
                return this._totpasexField;
            }
            set {
                this._totpasexField = value;
            }
        }
        
        /// <remarks/>
        public double _patrliq {
            get {
                return this._patrliqField;
            }
            set {
                this._patrliqField = value;
            }
        }
        
        /// <remarks/>
        public double _moncobpart {
            get {
                return this._moncobpartField;
            }
            set {
                this._moncobpartField = value;
            }
        }
        
        /// <remarks/>
        public double _patdep {
            get {
                return this._patdepField;
            }
            set {
                this._patdepField = value;
            }
        }
        
        /// <remarks/>
        public string _fecha {
            get {
                return this._fechaField;
            }
            set {
                this._fechaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void cns_ind_liqCompletedEventHandler(object sender, cns_ind_liqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_ind_liqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_ind_liqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _indicadores Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_indicadores)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591