//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Sitio_Privado.CartolaResumida {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tann_cartola_resumidaSoap", Namespace="http://servicios.tanner.cl/cartolaresumida")]
    public partial class tann_cartola_resumida : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cns_total_generalOperationCompleted;
        
        private System.Threading.SendOrPostCallback cns_consulta_cuentaspisysOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tann_cartola_resumida() {
            this.Url = global::Sitio_Privado.Properties.Settings.Default.Sitio_Privado_CartolaResumida_tann_cartola_resumida;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cns_total_generalCompletedEventHandler cns_total_generalCompleted;
        
        /// <remarks/>
        public event cns_consulta_cuentaspisysCompletedEventHandler cns_consulta_cuentaspisysCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/cartolaresumida/cns_total_general", RequestNamespace="http://servicios.tanner.cl/cartolaresumida", ResponseNamespace="http://servicios.tanner.cl/cartolaresumida", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _cartola cns_total_general(string _rut, short _secuencia) {
            object[] results = this.Invoke("cns_total_general", new object[] {
                        _rut,
                        _secuencia});
            return ((_cartola)(results[0]));
        }
        
        /// <remarks/>
        public void cns_total_generalAsync(string _rut, short _secuencia) {
            this.cns_total_generalAsync(_rut, _secuencia, null);
        }
        
        /// <remarks/>
        public void cns_total_generalAsync(string _rut, short _secuencia, object userState) {
            if ((this.cns_total_generalOperationCompleted == null)) {
                this.cns_total_generalOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_total_generalOperationCompleted);
            }
            this.InvokeAsync("cns_total_general", new object[] {
                        _rut,
                        _secuencia}, this.cns_total_generalOperationCompleted, userState);
        }
        
        private void Oncns_total_generalOperationCompleted(object arg) {
            if ((this.cns_total_generalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_total_generalCompleted(this, new cns_total_generalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://servicios.tanner.cl/cartolaresumida/cns_consulta_cuentaspisys", RequestNamespace="http://servicios.tanner.cl/cartolaresumida", ResponseNamespace="http://servicios.tanner.cl/cartolaresumida", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public _cuentaspisys cns_consulta_cuentaspisys(string _rut) {
            object[] results = this.Invoke("cns_consulta_cuentaspisys", new object[] {
                        _rut});
            return ((_cuentaspisys)(results[0]));
        }
        
        /// <remarks/>
        public void cns_consulta_cuentaspisysAsync(string _rut) {
            this.cns_consulta_cuentaspisysAsync(_rut, null);
        }
        
        /// <remarks/>
        public void cns_consulta_cuentaspisysAsync(string _rut, object userState) {
            if ((this.cns_consulta_cuentaspisysOperationCompleted == null)) {
                this.cns_consulta_cuentaspisysOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncns_consulta_cuentaspisysOperationCompleted);
            }
            this.InvokeAsync("cns_consulta_cuentaspisys", new object[] {
                        _rut}, this.cns_consulta_cuentaspisysOperationCompleted, userState);
        }
        
        private void Oncns_consulta_cuentaspisysOperationCompleted(object arg) {
            if ((this.cns_consulta_cuentaspisysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cns_consulta_cuentaspisysCompleted(this, new cns_consulta_cuentaspisysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner.cl/cartolaresumida")]
    public partial class _cartola {
        
        private string _rutField;
        
        private string _periodoField;
        
        private double _saldocajaField;
        
        private double _totalrentafijaField;
        
        private double _instrfField;
        
        private double _ffmmrfField;
        
        private double _totalrentavariField;
        
        private double _accnacionField;
        
        private double _ffmmrvField;
        
        private double _fwdcompraField;
        
        private double _fwdventaField;
        
        private double _totsimulField;
        
        private double _totinversionesField;
        
        /// <remarks/>
        public string _rut {
            get {
                return this._rutField;
            }
            set {
                this._rutField = value;
            }
        }
        
        /// <remarks/>
        public string _periodo {
            get {
                return this._periodoField;
            }
            set {
                this._periodoField = value;
            }
        }
        
        /// <remarks/>
        public double _saldocaja {
            get {
                return this._saldocajaField;
            }
            set {
                this._saldocajaField = value;
            }
        }
        
        /// <remarks/>
        public double _totalrentafija {
            get {
                return this._totalrentafijaField;
            }
            set {
                this._totalrentafijaField = value;
            }
        }
        
        /// <remarks/>
        public double _instrf {
            get {
                return this._instrfField;
            }
            set {
                this._instrfField = value;
            }
        }
        
        /// <remarks/>
        public double _ffmmrf {
            get {
                return this._ffmmrfField;
            }
            set {
                this._ffmmrfField = value;
            }
        }
        
        /// <remarks/>
        public double _totalrentavari {
            get {
                return this._totalrentavariField;
            }
            set {
                this._totalrentavariField = value;
            }
        }
        
        /// <remarks/>
        public double _accnacion {
            get {
                return this._accnacionField;
            }
            set {
                this._accnacionField = value;
            }
        }
        
        /// <remarks/>
        public double _ffmmrv {
            get {
                return this._ffmmrvField;
            }
            set {
                this._ffmmrvField = value;
            }
        }
        
        /// <remarks/>
        public double _fwdcompra {
            get {
                return this._fwdcompraField;
            }
            set {
                this._fwdcompraField = value;
            }
        }
        
        /// <remarks/>
        public double _fwdventa {
            get {
                return this._fwdventaField;
            }
            set {
                this._fwdventaField = value;
            }
        }
        
        /// <remarks/>
        public double _totsimul {
            get {
                return this._totsimulField;
            }
            set {
                this._totsimulField = value;
            }
        }
        
        /// <remarks/>
        public double _totinversiones {
            get {
                return this._totinversionesField;
            }
            set {
                this._totinversionesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.tanner.cl/cartolaresumida")]
    public partial class _cuentaspisys {
        
        private string rutField;
        
        private string[] numcuentaField;
        
        /// <remarks/>
        public string rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
            }
        }
        
        /// <remarks/>
        public string[] numcuenta {
            get {
                return this.numcuentaField;
            }
            set {
                this.numcuentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void cns_total_generalCompletedEventHandler(object sender, cns_total_generalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_total_generalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_total_generalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _cartola Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_cartola)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void cns_consulta_cuentaspisysCompletedEventHandler(object sender, cns_consulta_cuentaspisysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cns_consulta_cuentaspisysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cns_consulta_cuentaspisysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public _cuentaspisys Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((_cuentaspisys)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591